#UPF pod deployment
apiVersion: v1
kind: Pod
metadata:
  name: jyoti-upf
  namespace: truminds
  annotations:
    k8s.v1.cni.cncf.io/networks: host-net1
  labels:
    app: trucore-upf
spec:
  nodeName: k8worker-team
  containers:
  - image: trucore-upf:5july2023
    imagePullPolicy: Never
    name: trucore-upf
    env:
    - name: DOCKER_OPTS
      value: "--cap-add=NET_ADMIN --device /dev/net/tun:/dev/net/tun"
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_ADMIN"]
    command:
    - sleep
    - inf
    volumeMounts:
    - name: dev
      mountPath: /dev
  volumes:
  - name: dev
    hostPath:
      path: /dev
  restartPolicy: Always
